// Umrah Readiness Checklist — a pre-trip audit that removes pilgrim anxiety.
// "Help first, monetise second" — every shoppable item links DIRECTLY to
// the relevant Amazon UK search (tagged `sunnahumrah-21`), Yesim eSIM
// (Travelpayouts marker `525646`), or our in-app hotel/flight pages.
//
// Each item supports a "missing" state: when the pilgrim says they DON'T
// have something, we slide down a help panel with affiliate options. Per
// the friend's spec — don't wait for them to click "View options"; trigger
// it when they say "I don't have this".
//
// Items are grouped into 'essential' (blocks performing ʿUmrah) and
// 'recommended' (makes life easier). Each item can be personalised:
//   - travelers === 'family' → unlock family-only items
//   - travelers === 'wheelchair' → unlock accessibility items

import { amazonUkSearch, yesimSaudi } from "./affiliate";

export const CHECKLIST_ITEMS = [
  // ─── ESSENTIAL ─────────────────────────────────────────────
  {
    id: "passport",
    tier: "essential",
    group_en: "Travel & entry",
    group_ar: "السّفر والدّخول",
    group_icon: "✈️",
    title_en: "Passport",
    title_ar: "جواز السّفر",
    info_en: "Must be valid for at least 6 months from your travel date.",
    info_ar: "صالح لستّة أشهر على الأقلّ من تاريخ السّفر.",
    missing_prompt_en: "You'll need a valid passport before travelling. If yours is expired or close to expiring, renew it as early as possible.",
    missing_prompt_ar: "تحتاج جوازًا صالحًا قبل السّفر. إن كان منتهيًا أو قريبًا من الانتهاء، فجدّده مبكّرًا.",
    actions: [
      { label_en: "Renew on GOV.UK", label_ar: "تجديد عبر GOV.UK", url: "https://www.gov.uk/renew-adult-passport", icon: "📘", external: true },
    ],
  },
  {
    id: "visa",
    tier: "essential",
    group_en: "Travel & entry",
    group_ar: "السّفر والدّخول",
    group_icon: "✈️",
    title_en: "ʿUmrah or tourist visa",
    title_ar: "تأشيرة العمرة أو السّياحة",
    info_en: "The Saudi e-Visa and tourist visa both allow ʿUmrah.",
    info_ar: "تأشيرة الزّيارة السّعوديّة الإلكترونيّة والسّياحيّة كلتاهما تسمحان بأداء العمرة.",
    missing_prompt_en: "You'll need a Saudi visa before travelling. The Tourist e-Visa is the fastest route — it's issued online in minutes and now allows ʿUmrah.",
    missing_prompt_ar: "تحتاج تأشيرة سعوديّة قبل السّفر. الـ e-Visa السّياحيّة أسرع طريق — تصدر إلكترونيًّا خلال دقائق وتسمح بأداء العمرة.",
    actions: [
      { label_en: "Apply for Saudi e-Visa", label_ar: "قدّم طلب التّأشيرة الإلكترونيّة", url: "https://visa.visitsaudi.com", icon: "🌐", external: true },
    ],
  },
  {
    id: "flights",
    tier: "essential",
    group_en: "Travel & entry",
    group_ar: "السّفر والدّخول",
    group_icon: "✈️",
    title_en: "Flights booked",
    title_ar: "حجز الطّيران",
    info_en: "Book return flights early — Ramadan & Hajj seasons fill up fast.",
    info_ar: "احجز الذّهاب والعودة مبكّرًا — مواسم رمضان والحجّ تمتلئ بسرعة.",
    missing_prompt_en: "You'll need return flights to Jeddah or Madinah. Book early for the best prices, especially around Ramadan.",
    missing_prompt_ar: "تحتاج رحلات ذهاب وعودة إلى جدّة أو المدينة. احجز مبكّرًا للحصول على أفضل سعر، خاصّةً حول رمضان.",
    actions: [
      { label_en: "Compare flights", label_ar: "قارن الرّحلات", to: "/hotels", icon: "🔍" },
    ],
  },
  {
    id: "hotel",
    tier: "essential",
    group_en: "Accommodation",
    group_ar: "الإقامة",
    group_icon: "🏨",
    title_en: "Hotel or place to stay",
    title_ar: "فندق أو مكان إقامة",
    info_en: "Pick a hotel close to the Ḥaram so you can walk to prayers easily.",
    info_ar: "اختر فندقًا قريبًا من الحرم لتمشي إلى الصّلوات براحة.",
    missing_prompt_en: "Stay close to the Ḥaram — every minute saved walking is one more rakʿah. Book early; rooms near Gate 1 fill fast.",
    missing_prompt_ar: "اسكن قرب الحرم — كلّ دقيقة توفّرها مشيًا تكسبك ركعةً. احجز مبكّرًا؛ الغرف قرب البوّابة ١ تمتلئ بسرعة.",
    actions: [
      { label_en: "View hotels", label_ar: "استعرض الفنادق", to: "/hotels", icon: "🏨" },
      { label_en: "Or full Umrah packages", label_ar: "أو باقات عمرة كاملة", to: "/packages", icon: "🎁" },
    ],
  },
  {
    id: "miqat",
    tier: "essential",
    group_en: "Religious preparation",
    group_ar: "التّهيئة الشّرعيّة",
    group_icon: "📍",
    title_en: "Know your Mīqāt",
    title_ar: "اعرف ميقاتك",
    info_en: "The Mīqāt is the boundary where you enter Iḥrām. Most pilgrims enter Iḥrām on the plane — announced by the captain.",
    info_ar: "الميقات هو الحدّ الذي تدخل منه في الإحرام. معظم الحجّاج يدخلون الإحرام على متن الطّائرة — يُعلن الطّيّار عن ذلك.",
    missing_prompt_en: "It's important to know which Mīqāt boundary you'll cross — pilgrims from London usually enter Iḥrām on the plane.",
    missing_prompt_ar: "من المهمّ معرفة أيّ ميقات ستتجاوزه — حجّاج لندن غالبًا يحرمون على متن الطّائرة.",
    actions: [
      { label_en: "See the 6 Mīqāt", label_ar: "استعرض المواقيت السّتّة", to: "/miqat", icon: "📍" },
    ],
  },
  {
    id: "ihram-men",
    tier: "essential",
    group_en: "Clothing",
    group_ar: "اللّباس",
    group_icon: "👕",
    title_en: "♂️ Iḥrām garments (two white cloths)",
    title_ar: "♂️ ثوبا الإحرام (إزار ورداء)",
    info_en: "Two unstitched white cloths — izār (lower wrap) + ridāʾ (upper wrap). Bring a spare in case one gets dirty.",
    info_ar: "قطعتان غير مخيطتين بيضاوان — إزار (الأسفل) ورداء (الأعلى). خذ احتياطيّة تحسّبًا لتلطّخ إحداهما.",
    missing_prompt_en: "You'll need at least one set of Iḥrām garments — two unstitched white cloths. We recommend bringing a spare.",
    missing_prompt_ar: "تحتاج على الأقلّ زوجًا واحدًا من ثياب الإحرام — قطعتان بيضاوان غير مخيطتين. ننصح بإحضار احتياطيّ.",
    actions: [
      { label_en: "Shop Iḥrām on Amazon UK", label_ar: "تسوّق الإحرام عبر Amazon UK", url: amazonUkSearch("ihram set mens 2 piece cotton"), icon: "🛒", external: true },
    ],
  },
  {
    id: "modest-women",
    tier: "essential",
    group_en: "Clothing",
    group_ar: "اللّباس",
    group_icon: "👕",
    title_en: "♀️ Modest clothing",
    title_ar: "♀️ ملابس محتشمة",
    info_en: "Loose modest clothing (any colour). No niqāb, no gloves during Iḥrām.",
    info_ar: "ملابس فضفاضة ومحتشمة (بأيّ لون). ولا نقاب ولا قفّازين أثناء الإحرام.",
    missing_prompt_en: "Bring modest, breathable clothing in any colour. Long abāyahs work well in Makkah's heat.",
    missing_prompt_ar: "خذي ملابس محتشمة فضفاضة بأيّ لون. العباءات الطّويلة تناسب حرّ مكّة.",
    actions: [
      { label_en: "Shop abāyahs on Amazon UK", label_ar: "تسوّق العباءات عبر Amazon UK", url: amazonUkSearch("abaya women umrah travel"), icon: "🛒", external: true },
    ],
  },
  {
    id: "ihram-knowledge",
    tier: "essential",
    group_en: "Religious preparation",
    group_ar: "التّهيئة الشّرعيّة",
    group_icon: "📖",
    title_en: "Read the ʿUmrah step-by-step guide",
    title_ar: "اقرأ دليل العمرة خطوة بخطوة",
    info_en: "Walk through the 15 steps at least once before you travel — so nothing feels unfamiliar on arrival.",
    info_ar: "مُرّ على الخطوات الخمس عشرة مرّةً واحدة قبل السّفر — حتّى لا تجد شيئًا غريبًا عند الوصول.",
    missing_prompt_en: "Don't go in cold — walk through the 15 steps once before you travel. Tap below to start.",
    missing_prompt_ar: "لا تذهب بلا تحضير — مُرّ على الخطوات الخمس عشرة مرّةً قبل السّفر. اضغط أدناه للبدء.",
    actions: [
      { label_en: "Start guided steps", label_ar: "ابدأ الخطوات المرشدة", to: "/tour", icon: "📘" },
    ],
  },

  // ─── RECOMMENDED ───────────────────────────────────────────
  {
    id: "crossbody",
    tier: "recommended",
    group_en: "Travel essentials",
    group_ar: "أساسيّات السّفر",
    group_icon: "🎒",
    title_en: "Small pouch / cross-body bag",
    title_ar: "حقيبة صغيرة / حقيبة بحمّالة",
    info_en: "For your phone, hotel card, cash, and keys — leave valuables in the hotel safe.",
    info_ar: "لهاتفك وبطاقة الفندق والنّقود والمفاتيح — ودع الأغراض الثّمينة في خزنة الفندق.",
    missing_prompt_en: "A small cross-body keeps your phone, hotel card, and cash safe inside the masjid. Pickpocketing is rare but happens in crowds.",
    missing_prompt_ar: "حقيبة صغيرة تحمي هاتفك وبطاقة الفندق ونقودك داخل المسجد. السّرقة نادرة لكنّها تحدث في الزّحام.",
    actions: [
      { label_en: "Shop cross-body bags on Amazon UK", label_ar: "تسوّق الحقائب عبر Amazon UK", url: amazonUkSearch("crossbody bag anti theft travel"), icon: "🛒", external: true },
    ],
  },
  {
    id: "suitcase",
    tier: "recommended",
    group_en: "Travel essentials",
    group_ar: "أساسيّات السّفر",
    group_icon: "🎒",
    title_en: "Suitcase or cabin bag",
    title_ar: "حقيبة سفر أو يد",
    info_en: "Choose based on your stay length. Many packages include laundry service.",
    info_ar: "اختر حسب مدّة إقامتك. كثير من الباقات تشمل خدمة الغسيل.",
    missing_prompt_en: "Pick a size based on your stay length. Cabin-only saves baggage fees if you travel light.",
    missing_prompt_ar: "اختر الحجم حسب مدّة الإقامة. الكابينة فقط توفّر رسوم الأمتعة إن سافرت بخفّة.",
    actions: [
      { label_en: "Shop suitcases on Amazon UK", label_ar: "تسوّق حقائب السّفر عبر Amazon UK", url: amazonUkSearch("cabin suitcase lightweight 4 wheel"), icon: "🛒", external: true },
    ],
  },
  {
    id: "shoes",
    tier: "recommended",
    group_en: "Travel essentials",
    group_ar: "أساسيّات السّفر",
    group_icon: "🎒",
    title_en: "Comfortable walking shoes / sandals",
    title_ar: "حذاء مشي مريح / صندل",
    info_en: "You'll walk far more than you expect. Men: no shoes covering the ankle bone during Iḥrām — sandals or flip-flops are ideal.",
    info_ar: "ستمشي أكثر بكثير ممّا تتوقّع. ♂️ للرّجال: لا لبس يستر الكعبين في الإحرام — الصّنادل أو الشّبشب مثاليّ.",
    missing_prompt_en: "You'll walk 10–15 km some days. Men in Iḥrām need sandals or flip-flops — never shoes that cover the ankle bone.",
    missing_prompt_ar: "ستمشي ١٠–١٥ كم بعض الأيّام. ♂️ الرّجال في الإحرام يحتاجون صنادل أو شبشب — لا حذاء يستر الكعبين.",
    actions: [
      { label_en: "Shop iḥrām sandals on Amazon UK", label_ar: "تسوّق صنادل الإحرام عبر Amazon UK", url: amazonUkSearch("ihram sandals mens hajj umrah"), icon: "🛒", external: true },
    ],
  },
  {
    id: "unscented",
    tier: "recommended",
    group_en: "Personal care",
    group_ar: "العناية الشّخصيّة",
    group_icon: "🧼",
    title_en: "Unscented soap & shampoo",
    title_ar: "صابون وشامبو غير معطّرين",
    info_en: "Scented products count as perfume — forbidden after the Talbiyah. Keep unscented ones ready.",
    info_ar: "المنتجات المعطّرة تُعدّ طيبًا — وهي محظورة بعد التّلبية. فاحرص على غير المعطّر.",
    missing_prompt_en: "Scented soaps & shampoos count as perfume — forbidden once you've entered Iḥrām. Get a small unscented set before you fly.",
    missing_prompt_ar: "الصّابون والشّامبو المعطّر يُعدّ طيبًا — محظور بعد الدّخول في الإحرام. خذ مجموعة صغيرة غير معطّرة قبل السّفر.",
    actions: [
      { label_en: "Shop unscented on Amazon UK", label_ar: "تسوّق غير المعطّر عبر Amazon UK", url: amazonUkSearch("unscented soap shampoo travel size"), icon: "🛒", external: true },
    ],
  },
  {
    id: "hygiene",
    tier: "recommended",
    group_en: "Personal care",
    group_ar: "العناية الشّخصيّة",
    group_icon: "🧼",
    title_en: "Toothbrush, unscented toothpaste, comb",
    title_ar: "فرشاة، معجون غير معطّر، مشط",
    info_en: "Travel-size so they fit in your Iḥrām-stage pouch.",
    info_ar: "أحجام السّفر لتناسب حقيبة الإحرام.",
    missing_prompt_en: "Travel-size sets so they fit in your Iḥrām pouch. Mint toothpaste with strong perfume oils should be avoided.",
    missing_prompt_ar: "أحجام صغيرة لتناسب حقيبة الإحرام. وتجنّب معاجين النّعناع ذات زيوت العطر القويّة.",
    actions: [
      { label_en: "Shop travel hygiene on Amazon UK", label_ar: "تسوّق العناية للسّفر عبر Amazon UK", url: amazonUkSearch("travel toothbrush toothpaste comb set"), icon: "🛒", external: true },
    ],
  },
  {
    id: "sim",
    tier: "recommended",
    group_en: "Tech & practical",
    group_ar: "التّقنية والعمليّات",
    group_icon: "📱",
    title_en: "eSIM or roaming plan",
    title_ar: "eSIM أو باقة تجوال",
    info_en: "Data in Saudi can be expensive on roaming. An eSIM activates in 2 minutes and is usually cheaper.",
    info_ar: "بيانات التّجوال في السّعوديّة قد تكون مرتفعة. شريحة eSIM تُفعّل خلال دقيقتين وغالبًا أرخص.",
    missing_prompt_en: "Avoid roaming bill shock. An eSIM activates in 2 minutes and saves you finding a kiosk on arrival.",
    missing_prompt_ar: "تجنّب صدمة فاتورة التّجوال. شريحة eSIM تُفعّل في دقيقتين وتغنيك عن البحث عن كشك عند الوصول.",
    actions: [
      { label_en: "Get a Saudi eSIM (Yesim)", label_ar: "احصل على eSIM للسعوديّة (Yesim)", url: yesimSaudi(), icon: "📡", external: true },
    ],
  },
  {
    id: "powerbank",
    tier: "recommended",
    group_en: "Tech & practical",
    group_ar: "التّقنية والعمليّات",
    group_icon: "📱",
    title_en: "Power bank",
    title_ar: "باور بانك",
    info_en: "Long days at the Ḥaram drain phones fast — carry a 10,000 mAh minimum.",
    info_ar: "الأيّام الطّويلة في الحرم تستنزف البطّاريّات — احمل ١٠٠٠٠ ملّي أمبير على الأقلّ.",
    missing_prompt_en: "10–15 hour days at the Ḥaram drain phones fast. A 10,000 mAh power bank covers a full day.",
    missing_prompt_ar: "أيّام ١٠–١٥ ساعة في الحرم تستنزف البطّاريّة. ١٠٠٠٠ ملّي أمبير تكفي يومًا كاملًا.",
    actions: [
      { label_en: "Shop power banks on Amazon UK", label_ar: "تسوّق باور بانك عبر Amazon UK", url: amazonUkSearch("power bank 10000 mah usb c fast charge"), icon: "🛒", external: true },
    ],
  },
  {
    id: "bookings",
    tier: "recommended",
    group_en: "Tech & practical",
    group_ar: "التّقنية والعمليّات",
    group_icon: "📱",
    title_en: "Booking confirmations saved (offline)",
    title_ar: "حفظ تأكيدات الحجز (دون إنترنت)",
    info_en: "Screenshots of flight, hotel, and visa — in case Wi-Fi fails at immigration.",
    info_ar: "لقطات شاشة من الطّيران والفندق والتّأشيرة — تحسّبًا لانقطاع الإنترنت عند الجوازات.",
    missing_prompt_en: "Screenshot all confirmations and save them in your phone's Files app. Useful if Wi-Fi fails at immigration.",
    missing_prompt_ar: "خذ لقطات شاشة لكلّ التّأكيدات واحفظها في تطبيق الملفّات. مفيدة إن انقطع الإنترنت عند الجوازات.",
  },
  {
    id: "meds",
    tier: "recommended",
    group_en: "Health",
    group_ar: "الصّحّة",
    group_icon: "💊",
    title_en: "Personal medication",
    title_ar: "أدويتك الشّخصيّة",
    info_en: "Bring enough for the full trip plus 3 extra days. Keep them in your hand luggage.",
    info_ar: "خذ كمّيّة تكفي الرّحلة كاملة + ٣ أيّام احتياطيّة. واحملها في حقيبة اليد.",
    missing_prompt_en: "If you take regular medication, bring enough for the trip + 3 extra days. Keep it in hand luggage in case checked bags get delayed.",
    missing_prompt_ar: "إن كنت تأخذ دواءً منتظمًا، فخذ كمّيّة تكفي الرّحلة + ٣ أيّام. واحملها في حقيبة اليد تحسّبًا لتأخّر الأمتعة.",
  },
  {
    id: "zamzam",
    tier: "recommended",
    group_en: "Health",
    group_ar: "الصّحّة",
    group_icon: "💊",
    title_en: "Reusable water bottle / Zamzam flask",
    title_ar: "قنّينة ماء / إبريق زمزم",
    info_en: "Stay hydrated. A small flask also lets you carry Zamzam back to your hotel.",
    info_ar: "ابقَ متروّيًا. إبريق صغير يتيح لك حمل زمزم إلى فندقك.",
    missing_prompt_en: "A 1L flask keeps you hydrated and lets you carry Zamzam back to your hotel. The Ḥaram has refill stations everywhere.",
    missing_prompt_ar: "إبريق ١ لتر يبقيك متروّيًا ويتيح لك حمل زمزم للفندق. ومحطّات تعبئة منتشرة في الحرم.",
    actions: [
      { label_en: "Shop Zamzam flasks on Amazon UK", label_ar: "تسوّق قنّينة زمزم عبر Amazon UK", url: amazonUkSearch("zamzam water bottle insulated flask"), icon: "🛒", external: true },
    ],
  },
  {
    id: "family-kids",
    tier: "recommended",
    travelers_only: "family",
    group_en: "Family",
    group_ar: "العائلة",
    group_icon: "👨‍👩‍👧",
    title_en: "Children's essentials",
    title_ar: "ضروريّات الأطفال",
    info_en: "Snacks, small toys for tawāf rest breaks, a child carrier, and spare clothes.",
    info_ar: "وجبات خفيفة، ألعاب صغيرة لاستراحات الطّواف، حمّالة أطفال، وملابس احتياطيّة.",
    missing_prompt_en: "Children get tired during long days. A carrier, snacks, a small toy, and spare clothes make a huge difference.",
    missing_prompt_ar: "الأطفال يتعبون في الأيّام الطّويلة. حمّالة الأطفال والوجبات الخفيفة ولعبة صغيرة وملابس احتياطيّة تُحدث فرقًا كبيرًا.",
    actions: [
      { label_en: "Shop child carriers on Amazon UK", label_ar: "تسوّق حمّالات الأطفال عبر Amazon UK", url: amazonUkSearch("baby carrier ergonomic travel hiking"), icon: "🛒", external: true },
    ],
  },
  {
    id: "wheelchair",
    tier: "recommended",
    travelers_only: "wheelchair",
    group_en: "Accessibility",
    group_ar: "الاحتياجات الخاصّة",
    group_icon: "♿",
    title_en: "Wheelchair arrangements",
    title_ar: "ترتيبات الكرسيّ المتحرّك",
    info_en: "Ṭawāf in a wheelchair is fully valid (Ibn Bāz). Dedicated lanes exist on the ground floor and upper mataf. You can hire a pusher near Gate 1.",
    info_ar: "الطّواف بالكرسيّ المتحرّك صحيح تمامًا (ابن باز). توجد ممرّات خاصّة في الدّور الأرضي والعلوي للمطاف. ويمكنك استئجار دافع عند البوّابة ١.",
    missing_prompt_en: "Pre-arrange a wheelchair if needed. Many ʿUmrah packages include this; otherwise hire on arrival near Gate 1.",
    missing_prompt_ar: "رتّب الكرسيّ المتحرّك مسبقًا إن احتجته. كثير من الباقات تشمله؛ أو استأجر عند الوصول قرب البوّابة ١.",
    actions: [
      { label_en: "Packages with wheelchair help", label_ar: "باقات بمساعدة الكرسيّ", to: "/packages", icon: "🎁" },
    ],
  },
];
