// Umrah Readiness Checklist — a pre-trip audit that removes pilgrim anxiety.
// "Help first, monetise second" — every shoppable item links into /shop,
// /hotels, or /packages (which already carry the affiliate tags).
//
// Items are grouped into 'essential' (blocks performing ʿUmrah) and
// 'recommended' (makes life much easier). Each item can be personalised:
//   - gender-specific (♂/♀) → hidden for the other gender
//   - travelers === 'family' → unlock the family-only items
//   - travelers === 'wheelchair' → unlock accessibility items

export const CHECKLIST_ITEMS = [
  // ─── ESSENTIAL ─────────────────────────────────────────────
  {
    id: "passport",
    tier: "essential",
    group_en: "Travel & entry",
    group_ar: "السّفر والدّخول",
    group_icon: "✈️",
    title_en: "Passport",
    title_ar: "جواز السّفر",
    info_en: "Must be valid for at least 6 months from your travel date.",
    info_ar: "صالح لستّة أشهر على الأقلّ من تاريخ السّفر.",
  },
  {
    id: "visa",
    tier: "essential",
    group_en: "Travel & entry",
    group_ar: "السّفر والدّخول",
    group_icon: "✈️",
    title_en: "ʿUmrah or tourist visa",
    title_ar: "تأشيرة العمرة أو السّياحة",
    info_en: "The Saudi e-Visa and tourist visa both allow ʿUmrah. Check your eligibility on visa.visitsaudi.com.",
    info_ar: "تأشيرة الزّيارة السّعوديّة الإلكترونيّة والسّياحيّة كلتاهما تسمحان بأداء العمرة. تحقّق من أهليّتك على visa.visitsaudi.com.",
  },
  {
    id: "flights",
    tier: "essential",
    group_en: "Travel & entry",
    group_ar: "السّفر والدّخول",
    group_icon: "✈️",
    title_en: "Flights booked",
    title_ar: "حجز الطّيران",
    info_en: "Book return flights early for the best prices — Ramadan & Hajj season fill up fast.",
    info_ar: "احجز الرّحلات الذّهاب والعودة مبكّرًا — مواسم رمضان والحجّ تمتلئ بسرعة.",
    shop_to: "/hotels",
    shop_en: "See flight options",
    shop_ar: "استعرض الرّحلات",
  },
  {
    id: "hotel",
    tier: "essential",
    group_en: "Accommodation",
    group_ar: "الإقامة",
    group_icon: "🏨",
    title_en: "Hotel or place to stay",
    title_ar: "فندق أو مكان إقامة",
    info_en: "Pick a hotel close to the Ḥaram so you can walk to prayers easily.",
    info_ar: "اختر فندقًا قريبًا من الحرم لتمشي إلى الصّلوات براحة.",
    shop_to: "/hotels",
    shop_en: "See hotels",
    shop_ar: "استعرض الفنادق",
  },
  {
    id: "miqat",
    tier: "essential",
    group_en: "Religious preparation",
    group_ar: "التّهيئة الشّرعيّة",
    group_icon: "📍",
    title_en: "Know your Mīqāt",
    title_ar: "اعرف ميقاتك",
    info_en: "The Mīqāt is the boundary where you enter Iḥrām. Most pilgrims enter Iḥrām on the plane — announced by the captain.",
    info_ar: "الميقات هو الحدّ المكانيّ الذي تدخل منه في الإحرام. معظم الحجّاج يدخلون الإحرام على متن الطّائرة — يُعلن الطّيّار عن ذلك.",
    learn_to: "/places",
    learn_en: "See the 5 Mīqāt",
    learn_ar: "استعرض المواقيت الخمسة",
  },
  {
    id: "ihram-men",
    tier: "essential",
    gender: "male", // hidden for women, shown for men and 'unknown'
    group_en: "Clothing",
    group_ar: "اللّباس",
    group_icon: "👕",
    title_en: "♂️ Iḥrām garments (two white cloths)",
    title_ar: "♂️ ثوبا الإحرام (إزار ورداء)",
    info_en: "Two unstitched white cloths — izār (lower wrap) + ridāʾ (upper wrap). Bring a spare in case one gets dirty.",
    info_ar: "قطعتان غير مخيطتين بيضاوان — إزار (الأسفل) ورداء (الأعلى). خذ احتياطيّة تحسّبًا لتلطّخ إحداهما.",
    shop_to: "/shop",
    shop_en: "See recommended Iḥrām",
    shop_ar: "استعرض الإحرام المقترح",
  },
  {
    id: "modest-women",
    tier: "essential",
    gender: "female",
    group_en: "Clothing",
    group_ar: "اللّباس",
    group_icon: "👕",
    title_en: "♀️ Modest clothing",
    title_ar: "♀️ ملابس محتشمة",
    info_en: "Loose modest clothing (any colour). No niqāb, no gloves during Iḥrām.",
    info_ar: "ملابس فضفاضة ومحتشمة (بأيّ لون). ولا نقاب ولا قفّازين أثناء الإحرام.",
  },
  {
    id: "ihram-knowledge",
    tier: "essential",
    group_en: "Religious preparation",
    group_ar: "التّهيئة الشّرعيّة",
    group_icon: "📖",
    title_en: "Read the ʿUmrah step-by-step guide",
    title_ar: "اقرأ دليل العمرة خطوة بخطوة",
    info_en: "Walk through the 15 steps at least once before you travel — so nothing feels unfamiliar on arrival.",
    info_ar: "مُرّ على الخطوات الخمس عشرة مرّةً واحدة قبل السّفر — حتّى لا تجد شيئًا غريبًا عند الوصول.",
    learn_to: "/tour",
    learn_en: "Start guided steps",
    learn_ar: "ابدأ الخطوات المرشدة",
  },

  // ─── RECOMMENDED ───────────────────────────────────────────
  {
    id: "crossbody",
    tier: "recommended",
    group_en: "Travel essentials",
    group_ar: "أساسيّات السّفر",
    group_icon: "🎒",
    title_en: "Small pouch / cross-body bag",
    title_ar: "حقيبة صغيرة / حقيبة بحمّالة",
    info_en: "For your phone, hotel card, cash, and keys — leave valuables in the hotel safe.",
    info_ar: "لهاتفك وبطاقة الفندق والنّقود والمفاتيح — ودع الأغراض الثّمينة في خزنة الفندق.",
    shop_to: "/shop",
    shop_en: "View options",
    shop_ar: "استعرض الخيارات",
  },
  {
    id: "suitcase",
    tier: "recommended",
    group_en: "Travel essentials",
    group_ar: "أساسيّات السّفر",
    group_icon: "🎒",
    title_en: "Suitcase or cabin bag",
    title_ar: "حقيبة سفر أو يد",
    info_en: "Choose based on your stay length. Many packages include laundry service.",
    info_ar: "اختر حسب مدّة إقامتك. كثير من الباقات تشمل خدمة الغسيل.",
    shop_to: "/shop",
    shop_en: "View options",
    shop_ar: "استعرض الخيارات",
  },
  {
    id: "shoes",
    tier: "recommended",
    group_en: "Travel essentials",
    group_ar: "أساسيّات السّفر",
    group_icon: "🎒",
    title_en: "Comfortable walking shoes / sandals",
    title_ar: "حذاء مشي مريح / صندل",
    info_en: "You'll walk far more than you expect. Men: no shoes covering the ankle bone during Iḥrām — sandals or flip-flops are ideal.",
    info_ar: "ستمشي أكثر بكثير ممّا تتوقّع. ♂️ للرّجال: لا لبس يستر الكعبين في الإحرام — الصّنادل أو الشّبشب مثاليّ.",
  },
  {
    id: "unscented",
    tier: "recommended",
    group_en: "Personal care",
    group_ar: "العناية الشّخصيّة",
    group_icon: "🧼",
    title_en: "Unscented soap & shampoo",
    title_ar: "صابون وشامبو غير معطّرين",
    info_en: "Scented products count as perfume — forbidden after the Talbiyah. Keep unscented ones ready.",
    info_ar: "المنتجات المعطّرة تُعدّ طيبًا — وهي محظورة بعد التّلبية. فاحرص على غير المعطّر.",
    shop_to: "/shop",
    shop_en: "View options",
    shop_ar: "استعرض الخيارات",
  },
  {
    id: "hygiene",
    tier: "recommended",
    group_en: "Personal care",
    group_ar: "العناية الشّخصيّة",
    group_icon: "🧼",
    title_en: "Toothbrush, unscented toothpaste, comb",
    title_ar: "فرشاة، معجون غير معطّر، مشط",
    info_en: "Travel-size so they fit in your Iḥrām-stage pouch.",
    info_ar: "أحجام السّفر لتناسب حقيبة الإحرام.",
  },
  {
    id: "sim",
    tier: "recommended",
    group_en: "Tech & practical",
    group_ar: "التّقنية والعمليّات",
    group_icon: "📱",
    title_en: "eSIM or roaming plan",
    title_ar: "eSIM أو باقة تجوال",
    info_en: "Data in Saudi can be expensive on roaming. An eSIM activates in 2 minutes and is usually cheaper.",
    info_ar: "بيانات التّجوال في السّعوديّة قد تكون مرتفعة. شريحة eSIM تُفعّل خلال دقيقتين وغالبًا أرخص.",
    shop_to: "/shop",
    shop_en: "View options",
    shop_ar: "استعرض الخيارات",
  },
  {
    id: "powerbank",
    tier: "recommended",
    group_en: "Tech & practical",
    group_ar: "التّقنية والعمليّات",
    group_icon: "📱",
    title_en: "Power bank",
    title_ar: "باور بانك",
    info_en: "Long days at the Ḥaram drain phones fast — carry a 10,000 mAh minimum.",
    info_ar: "الأيّام الطّويلة في الحرم تستنزف البطّاريّات — احمل ١٠٠٠٠ ملّي أمبير على الأقلّ.",
    shop_to: "/shop",
    shop_en: "View options",
    shop_ar: "استعرض الخيارات",
  },
  {
    id: "bookings",
    tier: "recommended",
    group_en: "Tech & practical",
    group_ar: "التّقنية والعمليّات",
    group_icon: "📱",
    title_en: "Booking confirmations saved (offline)",
    title_ar: "حفظ تأكيدات الحجز (دون إنترنت)",
    info_en: "Screenshots of flight, hotel, and visa — in case Wi-Fi fails at immigration.",
    info_ar: "لقطات شاشة من الطّيران والفندق والتّأشيرة — تحسّبًا لانقطاع الإنترنت عند الجوازات.",
  },
  {
    id: "meds",
    tier: "recommended",
    group_en: "Health",
    group_ar: "الصّحّة",
    group_icon: "💊",
    title_en: "Personal medication",
    title_ar: "أدويتك الشّخصيّة",
    info_en: "Bring enough for the full trip plus 3 extra days. Keep them in your hand luggage.",
    info_ar: "خذ كمّيّة تكفي الرّحلة كاملة + ٣ أيّام احتياطيّة. واحملها في حقيبة اليد.",
  },
  {
    id: "zamzam",
    tier: "recommended",
    group_en: "Health",
    group_ar: "الصّحّة",
    group_icon: "💊",
    title_en: "Reusable water bottle / Zamzam flask",
    title_ar: "قنّينة ماء / إبريق زمزم",
    info_en: "Stay hydrated. A small flask also lets you carry Zamzam back to your hotel.",
    info_ar: "ابقَ متروّيًا. إبريق صغير يتيح لك حمل زمزم إلى فندقك.",
    shop_to: "/shop",
    shop_en: "View options",
    shop_ar: "استعرض الخيارات",
  },
  {
    id: "family-kids",
    tier: "recommended",
    travelers_only: "family",
    group_en: "Family",
    group_ar: "العائلة",
    group_icon: "👨‍👩‍👧",
    title_en: "Children's essentials",
    title_ar: "ضروريّات الأطفال",
    info_en: "Snacks, small toys for tawāf rest breaks, a child carrier, and spare clothes.",
    info_ar: "وجبات خفيفة، ألعاب صغيرة لاستراحات الطّواف، حمّالة أطفال، وملابس احتياطيّة.",
  },
  {
    id: "wheelchair",
    tier: "recommended",
    travelers_only: "wheelchair",
    group_en: "Accessibility",
    group_ar: "الاحتياجات الخاصّة",
    group_icon: "♿",
    title_en: "Wheelchair arrangements",
    title_ar: "ترتيبات الكرسيّ المتحرّك",
    info_en: "Ṭawāf in a wheelchair is fully valid (Ibn Bāz). Dedicated lanes exist on the ground floor and upper mataf. You can hire a pusher near Gate 1.",
    info_ar: "الطّواف بالكرسيّ المتحرّك صحيح تمامًا (ابن باز). توجد ممرّات خاصّة في الدّور الأرضي والعلوي للمطاف. ويمكنك استئجار دافع عند البوّابة ١.",
  },
];
